[hal] Use enums with fixed type on C23 (#9486)
Clang 20 and GCC 13 fully support [enums with fixed underlying
type][N3030] in C23. This results in the HAL example failing to build in
Bazel with newer Apple clang, as the warning name for it changed.

[N3030]: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3030.htm

Apple clang 21 output (with #9482):

```
In file included from wpilibcExamples/src/main/cpp/examples/HAL/c/Robot.c:19:
In file included from bazel-out/darwin_arm64-fastbuild/bin/hal/_virtual_includes/wpiHal/wpi/hal/DriverStation.h:10:
bazel-out/darwin_arm64-fastbuild/bin/hal/_virtual_includes/wpiHal/wpi/hal/DriverStationTypes.h:31:1: error: enumeration types with a fixed underlying type are a C23 extension [-Werror,-Wc23-extensions]
   31 | HAL_ENUM(HAL_AllianceStationID) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/darwin_arm64-fastbuild/bin/hal/_virtual_includes/wpiHal/wpi/hal/Types.h:82:24: note: expanded from macro 'HAL_ENUM'
   82 | #define HAL_ENUM(name) HAL_ENUM_WITH_UNDERLYING_TYPE(name, int32_t)
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/darwin_arm64-fastbuild/bin/hal/_virtual_includes/wpiHal/wpi/hal/Types.h:73:13: note: expanded from macro 'HAL_ENUM_WITH_UNDERLYING_TYPE'
   73 |   enum name : type;                               \
      |             ^~~~~~
```

This enables usage of C fixed enums on C23 and above only, and cleans up
the now unnecessary warning disables in this repo. Note that this means
that any consumers using libclang to parse the header must now specify
`-std=c23` (requires clang 18 or later) to recognise the type name as
the enum.

Set the C standard to `gnu23` for the Bazel Linux host GCC toolchain to
exercise this path. (GNU extensions are required for `M_PI` and related
macros in thirdparty code like apriltag.)

Also fix the formatting for `HAL_ENUM_WITH_UNDERLYING_TYPE` whilst we're
here.