[wpilibc] Make SPI destructor virtual since SPI contains virtual functions
```
/home/tav/git/calcmogul/Robot-2020/src/main/cpp/adi/ADIS16470_IMU.cpp: In member function ‘void frc::ADIS16470_IMU::Close()’:
/home/tav/git/calcmogul/Robot-2020/src/main/cpp/adi/ADIS16470_IMU.cpp:427:3: error: deleting object of polymorphic class type ‘frc::SPI’ which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
  427 |   delete m_spi;
      |   ^~~~~~~~~~~~
```